# Generated by Django 4.2.4 on 2023-09-10 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemmanager', '0012_alter_item_id_alter_restock_id_alter_restockitem_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='itemmanager.item')),
            ],
        ),
    ]
