# Generated by Django 4.2.4 on 2023-09-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmanager', '0013_stocknumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='StockNumber',
        ),
    ]
